name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "fpbuh6vs3t7efnls8fn9ufvn"
  title = "Nov. 11, 2024: Meet to plan project procedure"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = "2024-11-11T05:00:00.000Z"
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
